name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build  # Replace with your build command

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout --orphan gh-pages
          git --no-pager add --all
          git --no-pager commit --message "GitHub Actions: Deploy to GitHub Pages"
          git branch -D main
          git branch -m main
          git push --force origin main:gh-pages

      - name: Cleanup
        run: |
          git checkout main
          git branch -D gh-pages

